Repository AY2223S1-CS2103T-W16-4/tp, pull requests merged in 2022-11, with the labels that each got.

#287 Fix invalid dates such as leap year
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/Birthday.java
  src/main/java/seedu/address/model/meeting/MeetingDate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
Labels: type.Bug, priority.High, severity.High

#288 Fix and make command format more consistent
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/AddProductCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteProductCommand.java
  src/main/java/seedu/address/logic/commands/EditClientCommand.java
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/commands/ViewClientCommand.java
  src/main/java/seedu/address/logic/commands/ViewMeetingCommand.java
Labels: type.Chore, type.Bug, severity.Low

#301 Update ppp
  docs/team/thing1thing2.md
Labels: type.Chore
