Repository AY2223S1-CS2103T-W16-4/tp, pull requests merged in 2022-10, with the labels that each got.

#112 Fix setMeeting
  src/main/java/seedu/address/model/meeting/NoConflictMeetingList.java
Labels: type.Bug, severity.High

#104 UG: Update addMeeting to use INDEX
  docs/UserGuide.md
Labels: type.Chore

#126 Add listMeeting command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListMeetingCommand.java
  src/main/java/seedu/address/logic/parser/MyInsuRecParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/MyInsuRec.java
  src/main/java/seedu/address/model/ReadOnlyMyInsuRec.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/storage/JsonSerializableMyInsuRec.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MeetingCard.java
  src/main/java/seedu/address/ui/MeetingListPanel.java
  src/main/resources/view/MeetingListCard.fxml
  src/main/resources/view/MeetingListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/address/logic/commands/ListMeetingCommandTest.java
  src/test/java/seedu/address/model/MyInsuRecTest.java
Labels: priority.High

#143 Add UI for viewMeeting
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CommandSpecific.java
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListMeetingCommand.java
  src/main/java/seedu/address/logic/commands/ViewMeetingCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MeetingDetailedView.java
  src/main/java/seedu/address/ui/MeetingDetailedViewPanel.java
  src/main/resources/view/MeetingDetailedView.fxml
  src/main/resources/view/MeetingDetailedViewPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
Labels: priority.High

#146 Make viewClient use new CommandResult constructor
  src/main/java/seedu/address/logic/commands/ViewClientCommand.java
Labels: severity.High

#151 Fix invocation error when viewClient without args
  src/main/java/seedu/address/logic/parser/ViewClientCommandParser.java
  src/test/java/seedu/address/logic/parser/ViewClientCommandParserTest.java
Labels: type.Bug, severity.Low

#150 Fix plurality of records
  src/main/java/seedu/address/ui/ClientListPanel.java
  src/main/java/seedu/address/ui/MeetingListPanel.java
Labels: severity.Low

#201 Change JAR file name in build.gradle
  build.gradle
Labels: type.Chore

#279 Fix all UG issues as per PE-D
  docs/UserGuide.md
Labels: User Guide

#217 ug update
  docs/images/listClient.png
  docs/images/listMeeting.png
  docs/images/listProduct.png
Labels: type.Chore
